ita-social-projects/SpaceToStudy-BackEnd

.gitignore, app.js, controllers/example.js, logger/logger.js, package-lock.json, package.json
Created Logger using winston:
- logs are sent to MongoDB and Console
- default configurations are used, e.g. logging level ('info') and timestamp (server time) etc
- catching and logging uncaughtException
- logs stored in DB will expire in 1 week
- replaced console.log with logger.info/logger.error
=> Added winston logger that logs to MongoDB and Console

middlewares/asyncWrapper.js
a function wrapper that handles errors in async code and makes code cleaner by eliminating try\catch blocks.
=> added a wrapper for async functions

consts/errors.js, controllers/admin.js, controllers/auth.js, controllers/example.js, controllers/user.js, middlewares/error.js, routes/admin.js, routes/auth.js, routes/example.js, routes/user.js, utils/errorsHelper.js
- removed try\catch from controllers (except for the delete method in the example controller due to the test conflict)
- applied function wrapper to all routes
- replaced WRONG_PATH with NOT_FOUND error (error in const + errorHelper in utils)
- added ability to log errors to console handled by error handler middleware
- added delete endpoint to the example route
=> Async wrapper implementation

middlewares/error.js
moved  logger.error(err) to the line 6 from the line 5
=> changed logger position in error middleware

emails/confirm-email.pug, emails/css/index.css, package-lock.json
added package-lock file, fixed font, fixed email link
=> added package-lock file, fixed font, fixed email link

consts/errors.js, middlewares/validation.js, routes/auth.js, utils/validationHelper.js, validation/schemas/signup.js
Added validation middleware for checking request body for valid data
=> added validation middleware for check

emails/css/index.css, emails/index.pug, emails/reset-password.pug
Added template for reset password and changed some styles
=> Added template for reset password

emails/confirm-email.pug
added info about link expiration to the confirm-email template
=> added text line to the confirm-email template about expiration

consts/errors.js, middlewares/idValidation.js, routes/admin.js, routes/example.js, routes/user.js
added middleware that validates id that comes from param
implemented middleware in routes
=> added middleware that validates incoming id

services/auth.js
moved emailConfirm status validation below password validation
=> changed validation order in login

consts/errors.js, controllers/email.js, cron-jobs/checkForLastLogin.js, routes/email.js, routes/index.js, services/auth.js, services/email.js, utils/mailer.js
- added send-email route
- added send-email controller
- moved `emailService.js` file from utils to service folder and renamed it to `email.js` to follow the pattern
- added custom error messages in case google API access token was not retrieved and email was not sent inside `mailer.js` file (utils)
=> added send-email endpoint

logger/logger.js
- added error stack tracing (helps in debugging)
- changed level to 'error' for DB (so only errors will be saved to DB logs)
- changed print format (made it more readable)
=> added error stack tracing, changed print format

emails/confirm-email.pug, emails/css/index.css, emails/index.js, emails/index.pug, emails/long-time-without-login.pug, emails/reset-password.pug
=> removed unnesessary space in pug

initialization/database.js
Add functionality to drop all collections of a local database before tests.
=> Drop collections of a local DB before tests

test/integration/controllers/email.spec.js
Write tests for Email Controller
=> add tests for email controller

jest.config.js, test/integration/controllers/auth.spec.js
Write tests for RefreshAccessToken, SendResetPasswordEmail, UpdatePassword endpoints
=> write tests for refresh, sendPass, resetPass

consts/errors.js, controllers/user.js, cron-jobs/checkForLastLogin.js, docs/admin/admin.yaml, docs/auth/auth-schema.yaml, docs/auth/auth.yaml, docs/user/user-schema.yaml, docs/user/user.yaml, routes/user.js, services/admin.js, services/auth.js, services/user.js, test/integration/controllers/admin.spec.js, test/integration/controllers/auth.spec.js, utils/mailer.js
User service: added `createUser`, `getUserByParam`, `updateUser` methods for internal use
applied User service instead of User model in Auth service 
updated swagger docs for `user`, `admin`, `auth`
fixed tests for `signup`
fixed error naming
=> refactored user service and fixed error naming

consts/errors.js, controllers/review.js, docs/review/review-schema.yaml, docs/review/review.yaml, models/review.js, routes/index.js, routes/review.js
Create review model, route and swagger
=> Feature/139/Create review model, route and swagger

controllers/student.js, models/student.js, services/student.js
Added student controller and service
=> created student service and controller

consts/errors.js, controllers/auth.js, routes/auth.js, services/auth.js, services/student.js, services/tutor.js, test/integration/controllers/auth.spec.js, utils/auth.js, validation/schemas/login.js
Changed auth services according to schemas, added google auth
=> Changed auth services according to schemas

controllers/subject.js, docs/subject/subject-schema.yaml, docs/subject/subject.yaml, models/subject.js, routes/subject.js, services/subject.js, test/integration/controllers/subject.spec.js
Implemented endpoint and test, modified model and documentation for subject
=> Subject implementation

consts/errors.js, consts/validation.js, docs/user/user-schema.yaml, docs/user/user.yaml, initialization/serverSetup.js, middlewares/appLanguage.js, models/student.js, models/tutor.js, models/user.js, routes/auth.js, routes/email.js, services/user.js, test/unit/middlewares/language.spec.js
refactored user model
added new fields
renamed language middleware file to reflect its idea
=> refactor user model, docs

controllers/location.js, routes/index.js, routes/location.js, services/location.js
Implemented Controller for countries and cities API
=> implemented api for countries and cities

docs/review/review-schema.yaml, docs/review/review.yaml, models/review.js
Refactored reivew model and documentation
=> Refactored review model and swagger

controllers/user.js, docs/user/user-schema.yaml, docs/user/user.yaml, models/user.js, routes/user.js, services/user.js, test/integration/controllers/user.spec.js, test/unit/middlewares/auth.spec.js
changed from :userId to :id in routes and controllers
rewrote tests for user
added default option for bookmarkedOffers in User Model
=> added tests for user, changed routes/model/swagger

controllers/review.js, routes/review.js, services/review.js, test/integration/controllers/review.spec.js, utils/testUserAuth.js
Implemented review controller, service and integration tests.
=> Implemented controller, service and tests for review

package-lock.json
=> migrated to a new node v

controllers/review.js, jest.config.js, models/user.js, routes/review.js, routes/user.js, services/review.js, services/user.js
added virtuals so users/:id will get reviews field for a user
added /users/:id/reviews endpoint to show reviews only for a chosen user
=> added virtuals for reviews and /reviews endpoint for user

services/user.js, utils/reviews/reviewStatsAggregation.js
added review stats aggregation pipeline so we can calc amount of reviews for each rating
=> added review calc for each rating

models/offer.js, routes/offer.js, test/integration/controllers/offer.spec.js
added tests for offer entity controller
=> added tests for offer entity controller

models/subject.js, test/integration/controllers/subject.spec.js
=> refactored subject test

controllers/review.js, docs/review/review-schema.yaml, docs/review/review.yaml, models/offer.js, models/review.js, models/user.js, services/review.js, test/integration/controllers/review.spec.js, utils/getMatchOptions.js
Refactored review, added population to 'author' and 'offer' fields, updated documentation and tests, modified 'user' and 'offer' schemas to prevent duplication of 'id' in populated fields
=> Refactored review, added population and filtration

controllers/user.js, middlewares/setCurrentUserId.js, middlewares/setCurrentUserIdAndRole.js, routes/offer.js, routes/review.js, routes/user.js
=> added my profile endpoint

test/integration/controllers/email.spec.js
Refactored and fixed email test
=> Refactored and fixed email test

controllers/review.js, models/offer.js, models/review.js, models/user.js, routes/user.js, utils/reviews/reviewStatsAggregation.js
- added 2 fields to the user model: totalReviews and averageRating
- added aggregation pipeline that calculates averagerating and totalreviews for each user based on a role and saves it to the current document
- added pre, post and query middlewares that will use static method and update averageRating and totalReviews every time when a new review is added or one is updated or deleted
- fixed compound index, so now different users can leave a review to one user but the same offer
- added proper message for an enum validation in the model as an example
- removed role from the params and added it to a query
- changed routes from users/:id/:role to users/:id
- added a nested route users/:id/reviews so it will show all reviews that belong to that user
- removed totalreviews and averagerating …
=> added aggregation pipeline to calc avg and total reviews

consts/models.js, models/adminInvitation.js, models/category.js, models/offer.js, models/review.js, models/subject.js, models/token.js, models/user.js
Added file for models in folder consts and added refs of every model there
=> Added file for models in consts

docs/review/review.yaml, models/review.js, services/review.js
- Fix fields which we need to return for review 
- Refactor Swagger for reviews
=> Fix fields which we need to return for review 

test/integration/controllers/adminInvitation.spec.js
[Feature/236](https://github.com/ita-social-projects/SpaceToStudy-BackEnd/issues/236)
Refactored adminInvitation test
=> Refactored adminInvitation test

consts/validation.js, models/offer.js, models/user.js
[Feature/259](https://github.com/ita-social-projects/SpaceToStudy-BackEnd/issues/259)
Added validation messages for enums in offer and user models
=> Validation messages for enums

.github/workflows/main.yaml, .gitignore, sonar-project.properties
Changed configuration of sonarcloud
Changes:
=> Fix SonarCloud Coverage

consts/errors.js, consts/validation.js, controllers/cooperation.js, docs/cooperation/cooperation.schema.yaml, docs/cooperation/cooperation.yaml, models/cooperation.js, routes/cooperation.js, routes/index.js, services/cooperation.js
Implemented model, route, swagger for cooperation.
=> Implemented cooperation model, route, docs

docs/user/user-schema.yaml, docs/user/user.yaml, utils/reviews/reviewStatsAggregation.js
Updated swagger docs for user model
=> Updated swagger for user model

cron-jobs/checkForLastLogin.js, package.json
=> Fixed Cron jobs

controllers/category.js, routes/category.js, services/category.js
added route for getting all category names
=> added route for getting all category names

controllers/subject.js, docs/category/category.yaml, routes/category.js, routes/subject.js, services/subject.js
Added route '/subjects/names' for categories to get all names of subjects in specified category.
=> Added /subjects/names route

controllers/subject.js, services/subject.js
I have implemented:
- skip and limit
- filtering by name of subject
- getting subjects by default is sorted by quantity of total offers
=> Implemented filtering for subject

services/category.js
refactor getCategoriesNames endpoint
=> refactor getCategoriesNames endpoint

controllers/category.js, controllers/subject.js, models/category.js, routes/category.js, services/subject.js, test/integration/controllers/category.spec.js
- refactored getCategories, getNamesByCategoryId endpoints;
- fixed category model;
- fixed category tests.
=> Refactor categories and subjects

consts/categories.js, docs/category/category-schema.yaml, docs/category/category.yaml, docs/review/review.yaml, models/category.js, test/integration/controllers/category.spec.js
Added color for category schema
=> Added color field to category

consts/errors.js, models/category.js, models/cooperation.js, models/offer.js, models/review.js, models/subject.js, models/user.js, services/category.js
- Added validation messages for required fields
- Removed virtuals in cause of no need
- Refactored service functions by making them similar to our services structure
=> Refactored category model and service

controllers/offer.js, docs/offer/offer-schema.yaml, docs/offer/offer.yaml, models/offer.js, models/review.js, services/offer.js, utils/offers/offerAggregateOptions.js
Implemented filtering, sorting and pagination for offers
Added new fields to offer model
=> Implemented filtering, sorting and pagination for offers

controllers/user.js, services/user.js, test/integration/controllers/user.spec.js, utils/testUserAuth.js
=> Refactored test of users endpoints

docs/offer/offer-schema.yaml, docs/offer/offer.yaml, models/offer.js, test/integration/controllers/offer.spec.js, utils/offers/offerAggregateOptions.js
refactored offer model, docs, aggregate options and tests
=> Refactored offer

docs/cooperation/cooperation.schema.yaml, docs/user/user.yaml, services/category.js
Fixed category min max price by adding 0 values
=> Fixed category min max price

docs/user/user.yaml, models/user.js
Implemented deleting all offers when deleting or blocking user
=> Deleting all offers that are related to deleted user

services/category.js
Added sorting categories by quantity of field totalOffers
=> Added sorting categories by qty of offers

models/offer.js
Fixed bug in calculation totalOffers
=> Fixed totalOffers in subjects and categories

controllers/user.js, docs/user/user.yaml, models/user.js, services/user.js, test/integration/controllers/user.spec.js, validation/services/user.js
=> Fixed model of user and swagger

consts/categories.js, models/category.js
Capitalize first letter of category name
=> Added capitalizing letters for category in seeds

docs/offer/offer-schema.yaml, docs/offer/offer.yaml, docs/review/review.yaml, models/offer.js, models/review.js, services/offer.js, services/review.js, utils/offers/offerAggregateOptions.js
=> Fixed review and offer models

consts/errors.js, models/cooperation.js, models/offer.js, models/review.js, models/user.js, routes/cooperation.js, services/cooperation.js
Updated model of cooperation, refactored enum message in models by moving to separate validation function to make it common
=> Modified creation of cooperation

models/user.js, test/integration/controllers/review.spec.js
=> Fix review tests

docs/user/user.yaml, models/offer.js, routes/user.js, services/offer.js, test/integration/controllers/offer.spec.js, utils/offers/offerAggregateOptions.js, utils/testUserAuth.js
sorting offers by status
filtering by entered title or author name
route for getting all offers by userId
=> additinal offer filtering and route for getting all offers by user id

initialization/initialization.js, services/category.js, services/subject.js
Fixed sorting subjects and categories. 
Sorting is now done by a number of offers and update time.
Limit increased for JSON
How it was:
=> Fixed sorting subjects and categories. Limit increased for JSON

controllers/user.js, test/integration/controllers/user.spec.js
=> Fix user test

controllers/cooperation.js, models/cooperation.js, services/cooperation.js, utils/cooperations/coopsAggregateOptions.js
Changed aggregation for cooperations, changed cooperations model
=> Changed aggregation for cooperation

test/integration/controllers/auth.spec.js
=> Fix auth tests

models/category.js, services/offer.js, utils/cooperations/coopsAggregateOptions.js, utils/offers/offerAggregateOptions.js
Fixed aggregations for offer and coop, changed category model
=> Fixed aggregations for offer and coop

routes/cooperation.js, test/integration/controllers/cooperation.spec.js
=> Implemented cooperation tests 

controllers/cooperation.js, docs/cooperation/cooperation.schema.yaml, docs/cooperation/cooperation.yaml, models/cooperation.js, services/cooperation.js, utils/cooperations/coopsAggregateOptions.js
Added roles for initiator and receiver of coop
=> Added roles for initiator and receiver of coop

services/user.js
=> Fixed test of users

consts/models.js, docs/message/message-schema.yaml, models/message.js
Added message model
- model
- swagger
=> Added message model

controllers/course.js, docs/course/course.yaml, routes/course.js, routes/index.js, services/course.js, test/integration/controllers/course.spec.js
Implemented update a course:
Passed tests:
=> Implemented update a course

services/chat.js, test/integration/controllers/comment.spec.js
=> Fix comment test

controllers/notification.js, docs/notications/notification.yaml, routes/notification.js, services/notification.js, test/integration/controllers/course.spec.js, test/integration/controllers/notification.spec.js
=> add clear notifications endpoint

controllers/notification.js, docs/notications/notification.yaml, routes/notification.js, services/notification.js, test/integration/controllers/notification.spec.js
=> implemented delete notification by ID

controllers/course.js, docs/course/course.yaml, package-lock.json, routes/course.js, services/course.js, test/integration/controllers/course.spec.js
=> Created get one course endpoint

consts/models.js, docs/attachments/attachments-schema.yaml, models/attachments.js
=> Implemented schema for attachments

controllers/quiz.js, docs/quiz/quiz-schema.yaml, docs/quiz/quiz.yaml, models/quiz.js, routes/index.js, routes/quiz.js, services/quiz.js, test/integration/controllers/quiz.spec.js
=> implement creating a quiz

controllers/attachment.js, docs/attachments/attachment.yaml, models/attachment.js, models/quiz.js, routes/attachment.js, routes/index.js, services/attachment.js
* Implemented endpoint for getting all user attachments
* Implemented endpoint for deleting attachments by id
* updated swagger documentation
=> Implemented getAll and deleteById endpoints for attachment

controllers/quiz.js, docs/quiz/quiz.yaml, routes/quiz.js, services/quiz.js, test/integration/controllers/quiz.spec.js
=> Implemented Get all test endpoint

docs/course/course-schema.yaml, docs/course/course.yaml, docs/lesson/lesson-schema.yaml, docs/lesson/lesson.yaml, models/course.js, models/lesson.js, routes/course.js, routes/lesson.js, services/course.js, services/lesson.js, test/integration/controllers/course.spec.js, test/integration/controllers/lesson.spec.js
Refactored lesson's and course's model/service/test/docs
=> Refactor Lesson and Course

controllers/attachment.js
Modified get attachments due to Frontend needs and proper working
=> Modified get attachments

services/attachment.js, services/lesson.js, services/quiz.js
Solve sort problem that didn't work with lower case :
Before :
After :
--------------
Before : 
After:
=> (SP:0.5) Modify sorting in myResources

consts/errors.js, routes/message.js, services/message.js, utils/errorsHelper.js
Added creating chat on the first message
=> Added creating chat on the first message

docs/finishedQuiz/finishedQuiz.yaml, docs/lesson/lesson-schema.yaml, docs/lesson/lesson.yaml, models/lesson.js, services/lesson.js, test/integration/controllers/lesson.spec.js
Added content to lesson and fixed swagger for finished quizzes
=> Added content to lesson, fix swagger

consts/models.js, docs/resourcesCategory/resourcesCategory.schema.yaml, models/resourcesCategory.js
=> Resources category model created

controllers/question.js, controllers/resourcesCategory.js, docs/resourcesCategory/resourcesCategory.yaml, models/question.js, routes/resourcesCategory.js, services/question.js, services/resourcesCategory.js
=> added get resources category names and  category to question

docs/quiz/quiz-schema.yaml, models/quiz.js
=> Modify quiz model

services/question.js
Fixed creation of question. Now it's like this:
```
{
"title": "How are you?",
"answers": [
{
"text": "First answer",
"isCorrect": true
},
{
"text": "Second answer",
"isCorrect": false
}
],
"category": {
"_id": "6502ec2060ec37be943353e3"
},
"type": "multipleChoice"
}
```
=> Fixed question creation

controllers/resourcesCategory.js, docs/resourcesCategory/resourcesCategory.yaml, routes/resourcesCategory.js, services/resourcesCategory.js, test/integration/controllers/resourcesCategory.spec.js
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/102412173/00fd0e17-222d-408c-9905-aab8375a4de1
=> Create resource category endpoint

controllers/chat.js, docs/chat/chat.yaml, docs/quiz/quiz.yaml, docs/resourcesCategory/resourcesCategory.yaml, routes/chat.js, services/chat.js, test/integration/controllers/chat.spec.js
<details>
<summary>Preview</summary>
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/45912519/49616faf-8de9-43bc-94d8-d24fb06b4a1b
</details>
<details>
<summary>Test cases</summary>
</details>
=> Implemented delete chat endpoint

controllers/chat.js, docs/chat/chat.yaml, models/chat.js, routes/chat.js, services/chat.js, test/integration/controllers/chat.spec.js
<details>
<summary>Preview</summary>
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/45912519/7d4eef3a-0fd4-4e8e-bd83-c9b9a9f1fbca
</details>
<details>
<summary>Test cases</summary>
</details>
<details>
<summary>Swagger</summary>
</details>
=> Implemented delete for current user endpoint

controllers/message.js, docs/chat/chat.yaml, models/message.js, routes/message.js, services/message.js, test/integration/controllers/message.spec.js
<details>
<summary>Preview</summary>
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/45912519/c813d0f3-3948-45d9-9d02-708b3bbbe40f
</details>
<details>
<summary>Test cases</summary>
</details>
<details>
<summary>Swagger</summary>
</details>
<details>
<summary>Lint</summary>
</details>
=> Implemented clear chat history endpoint

controllers/attachment.js, controllers/lesson.js, controllers/question.js, controllers/quiz.js, utils/getCategoriesOption.js
Added possibility to categorize all resources
=> Adding util for categorization 

docs/offer/offer-schema.yaml, docs/offer/offer.yaml, models/offer.js, services/offer.js, test/integration/controllers/offer.spec.js
=> Add field for enrolledUsers in Offer

services/quiz.js
=> Added fields to getQuizById

controllers/question.js, routes/question.js, services/question.js
=> Added get question by id service

services/attachment.js
Description for attachment updates only in case we receive new description data
=> Updated edit attachment service

services/course.js
Created necessary methods for get courses
=> Added new method fields for get courses

consts/validation.js, docs/quiz/quiz-schema.yaml, docs/quiz/quiz.yaml, models/quiz.js, services/quiz.js
- added quiz view enum
- updated quiz-schema.yaml
- updated quiz.yaml
- updated quiz model
- updated quiz service
<details>
<summary>Swagger</summary>
</details>
<details>
<summary>Postman</summary>
<details>
=> Added settings for quiz

docs/questions/question.yaml, services/question.js
=> Updated getQuestionById service and added docs for it in Swagger

models/offer.js
Changed calculation of offers, only active offers are counted
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/17857767/03b98f53-4da2-409b-bb32-41bb40c1638a
=> Fixed active offers number

controllers/course.js, services/course.js
Created necessary fields for course service and controller
=> Added additional fields for search courses

services/quiz.js
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/56305508/9dd50936-3fd5-4c6e-b5a9-f37a2049eefa
**Fixed:** #669
=> Fixed quiz view types after created new questions

test/unit/cron-jobs/checkForLastLogin.spec.js, test/unit/services/token.spec.js
Fixed tests for token and checkForLastLogin
token
checkForLastLogin
=> Refactored token and checkForLastLogin tests

docs/lesson/lesson.yaml
=> fixed swagger

controllers/lesson.js, utils/cooperations/coopsAggregateOptions.js, utils/getSortOptions.js, utils/offers/offerAggregateOptions.js, utils/users/createAggregateOptions.js
Removed JSON parse for sorting, and fixed encoding for sort object from req.query
Fixed map is not a function for categories from req.query in resources controllers
=> fixed error with map is not a function and sorting

docs/course/course-schema.yaml, docs/course/course.yaml, models/course.js
Added order field for course section to display resources
=> Added order field for course section

docs/quiz/quiz.yaml, services/quiz.js
destructured settings from params and pass it to create method, also, changed yaml schema
=> added settings to create quiz

controllers/attachment.js, package.json
Fixed files uploading with non-ascii in the name 
Added and implemented iconv-lite decoding
=> Fixed files uploading with non-ascii in the name 

routes/note.js, services/note.js
- edited get notes service to filter notes that are private and author is not the current user
=> Added filter to get notes

docs/cooperation/cooperation-schema.yaml, docs/cooperation/cooperation.yaml, models/cooperation.js, services/cooperation.js, utils/cooperations/coopsAggregateOptions.js
- Added sections to the cooperation schema
- added activities array with **resourceType field = enum** and **resource field = mixed** to sections array
- changed swagger cooperation.yaml and cooperation-schema.yaml files
=> added sections to cooperation schema and updated swagger with controller

docs/cooperation/cooperation-schema.yaml, docs/cooperation/cooperation.yaml, models/cooperation.js, services/cooperation.js, test/integration/controllers/cooperation.spec.js
Added title to cooperation model and edited getCooperationById method
=> Added title to cooperation

services/resourcesCategory.js, test/integration/controllers/resourcesCategory.spec.js, test/unit/services/upload.spec.js
=> added coverage for ResourseCategory and Upload tests

controllers/finishedQuiz.js, routes/location.js, test/integration/controllers/finishedQuiz.spec.js, test/integration/controllers/location.spec.js
=> added coverage for finishedQuiz and location services

controllers/question.js, test/integration/controllers/cooperation.spec.js, test/integration/controllers/question.spec.js
=> Increased coverage of Question and Cooperation tests

test/integration/controllers/auth.spec.js
=> (SP: 1) Improve coverage of Auth tests

test/integration/controllers/review.spec.js, test/integration/controllers/user.spec.js
Increased coverage for `reviewStatsAggregation.js` and `createAggregateOptions.js` tests
<details>
<summary>reviewStatsAggregation.js</summary>
</details>
<details>
<summary>review.js controller</summary>
</details>
---
<details>
<summary>createAggregateOptions.js</summary>
</details>
<details>
<summary>user.js controller</summary>
</details>
**Resolved: #720**
=> Improved review and create aggregate coverage

services/note.js, test/integration/controllers/category.spec.js, test/integration/controllers/note.spec.js
=> added coverage for category and notes tests

services/course.js, services/offer.js, test/integration/controllers/course.spec.js, test/integration/controllers/offer.spec.js
Course service:
Offer service:
=> Improved coverage of course and offer services

test/integration/controllers/cooperation.spec.js, test/integration/controllers/offerAggregateOptions.spec.js, utils/offers/offerAggregateOptions.js
=> added coverage to CoopsAggregateOptions and OfferAggregateOptions tests

test/integration/controllers/attachments.spec.js, test/integration/controllers/quiz.spec.js
=> Added tests for attachments and quiz

models/user.js
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/63456632/45b56568-bf27-4969-83b6-fce27885b00a
=> added null as a default value for user nativeLanguage field

services/message.js, services/review.js, test/integration/controllers/message.spec.js, test/integration/controllers/review.spec.js
Improved review and message service coverage of branches
=> Improved review and message service coverage

utils/getUniqueFields.js, utils/testUserAuth.js
Fixed Sonar DoS issues security with `getUniqueFields.js` and `testUserAuth.js`
=> Fix Sonar issues for getUniqueFields and testUserAuth

middlewares/multer.js
Reduced upload file size from 10mb to 5 mb
=> Fixed multer security issue

docs/course/course.yaml, src/services/course.js
- populated lessons, attachments and quizzes fields for course sections
- changed course.yaml according to changes
=> populated resource fields for course sections

src/services/lesson.js, src/test/integration/controllers/user.spec.js
Increased tests coverage of `lesson` and `user` services
**Resolved: #736**
=> Improved lesson and user service coverage

src/controllers/attachment.js, src/services/attachment.js
Added updated attachement to response which is needed for [this PR](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/1790]) on Frontend
=> added attachment response to PATCH request

src/controllers/course.js
Implemented getting courses with filters (it works with PR [#1811](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/1811))
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/104922087/5ebfbd18-4c9d-4626-b91c-070e9338ef84
=> Implemented getting courses with filters

src/models/user.js, src/services/user.js, src/utils/users/photoCheck.js, src/validation/services/user.js
Added about tutor info into user model
needed for [FE Task](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/1830)
=> updated user model, serivice to update profeccional logic

src/consts/models.js, src/middlewares/coopSectionsValidation.js, src/models/cooperation.js, src/test/integration/controllers/cooperation.spec.js, src/test/unit/middlewares/coopSectionsValidation.spec.js, src/test/unit/utils/validateAttachment.spec.js, src/test/unit/utils/validateQuiz.spec.js, src/utils/cooperations/sections/validateAttachment.js, src/utils/cooperations/sections/validateCommonFields.js, src/utils/cooperations/sections/validateLesson.js, src/utils/cooperations/sections/validateQuiz.js
Fixed cooperation for saving and view. Removed questionValidation as we get id for now
=> Fixed cooperation for saving and view

src/models/attachment.js, src/models/lesson.js, src/models/quiz.js, src/test/integration/controllers/attachments.spec.js, src/test/integration/controllers/lesson.spec.js, src/test/integration/controllers/quiz.spec.js
Added for quizzes, lessons, attachments an availability field
=> Implement availability object

src/services/user.js, src/test/unit/services/user.spec.js
Added stepper support, refactored _user_ service
#790
=> Added stepper support

src/services/user.js, src/test/unit/services/user.spec.js
[fixDeleteBack.webm](https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/125293578/b2767af6-59f2-4432-ad93-5da3eb3c4162)
=> Fixed deletion bug

docs/category/category.yaml, docs/course/course.yaml, docs/review/review.yaml, src/consts/categories.js, src/services/category.js
Refactored swagger docs and some code to match actual category schema
=> Refactored swagger docs to match actual category schema

docs/user/user-schema.yaml, docs/user/user.yaml, src/services/user.js
Related to #2027
Now the getUserById response includes mainSubjects category appearance
=> Make getUserById endpoint return mainSubjects category appearance

src/services/subject.js
https://github.com/ita-social-projects/SpaceToStudy-BackEnd/assets/102433497/9df1ccad-a3cd-45a2-9a2a-d8940c4629d5
=> Fixed sorting for fetched subjects

azure-pipeline.yaml
Uncommented environmental stage for azure. 
#818
=> Uncommented stage

.github/workflows/main.yaml
This change ensures that the CI workflow runs on `feature` branches, allowing for more comprehensive testing and integration of feature-specific code before merging into the `develop` or `main` branches. This update will help maintain code quality and consistency across all `feature` branches by running the necessary checks and tests before integration.
=> Expanded workflow triggers to include feature branches #840

src/services/course.js, src/test/integration/controllers/course.spec.js, src/utils/resourceModelMapping.js
=> Added possibility to add resources to courses by creating a duplicate in resource collection

docs/user/user-schema.yaml, docs/user/user.yaml, src/models/user.js, src/services/user.js, src/validation/services/user.js
=> Added notificationSettings for the user in DB

docs/cooperation/cooperation.yaml, src/services/cooperation.js, src/test/integration/controllers/cooperation.spec.js, src/test/unit/cron-jobs/checkForLastLogin.spec.js
=> Added populate for initiator and receiver fields
