.eslintrc.json
.gitignore
jest.config.js
logger/logger.js
package-lock.json
package.json
test/helper.js
test/unit/controllers/example.spec.js

- Add dependencies for `jest`, `jest-sonar-reporter` and`supertest`;
- Remove dependenices for `mocha`, `chai` and `sinon`;
- Modify .gitignore, and the config for eslint;
- Add a config file for Jest;
- Modify the existing tests in accordance with the Jest rules.

Feature/65/Migrate tests to Jest

---

controllers/auth.js
docs/auth/auth-schema.yaml
docs/auth/auth.yaml
routes/auth.js
validation/schemas/resetPassword.js

Refactored the `/reset-password` endpoint to use params instead of the request body for the reset token.

Use params instead of body for the reset token

---

services/user.js

user found by email now returns with a role value instead of a role object

user returns with a role value instead of a role object

---

controllers/auth.js
services/auth.js
test/integration/controllers/auth.spec.js

made logout method return 204
updated tests
fixed cookie options: 
`secure` option is set to `false` now (for tests - http/postman) and will be changed to `true` when `'production'` (cookie will be sent on an encrypted connection - https)

logout returns 204, fixed tests

---

routes/cooperation.js

A little fix in routing for cooperation

Fix middleware naming in cooperation route

---

controllers/lesson.js
utils/getSortOptions.js

Changed sorting in "Get lessons" endpoint for the client needs and sort functionality
Passed tests of lessons:

Changed sorting in "Get lessons" endpoint

---

services/message.js

user_1, user_2
```
{
"_id": {
"$oid": "65568c34d556695822907892"
},
"text": "Hi!",
"clearedFor": [user_1],
}
```
**Previously:**
**user_1** could delete the message entirely from DB even if he is in `clearedFor` field (**user_2** could do this too)
**Now:**
Only **user_2** can delete the message entirely from DB (we need to have **user_1** in `clearedFor` field for this)

Fixed wrong deletion logic from the DB

---

cron-jobs/checkForLastLogin.js

Fixed request error

---

docs/comment/comment.yaml
docs/review/review-schema.yaml
docs/user/user.yaml

Changed swagger documentation for `Users` and `Comments`
Closes #646 #647

Changed swagger for Users and Comments

---

consts/validation.js
models/attachment.js
models/lesson.js
models/question.js
models/quiz.js
services/course.js

Expanded the resource type field, added needed fields to edit course

---

docs/user/user.yaml

Was added status code 400 (Bad Request) for `/users/{id}` PATCH method
**Fixed:** #650

Added 400 status code for patch users id

---

src/routes/lesson.js
src/test/integration/controllers/lesson.spec.js

Currently, students cannot get lessons, but they should be able to do so in order to learn the lesson on the Cooperation page according to the [frontend issue](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/1822).
To achieve this the placement of `router.use(restrictTo(TUTOR))` was changed.
The test was changed accordingly.

Enable students to access lessons

---

src/consts/validation.js
src/controllers/user.js
src/routes/user.js
src/test/integration/controllers/offer.spec.js
src/test/integration/controllers/user.spec.js
src/utils/offers/offerAggregateOptions.js

- Added two endpoints, one to deactivate user and another to activate him. I used the same approach as in `update` endpoint, so endpoint has `id`. I guess it can be used later for admin logic.
- Added a bunch of tests, some of them for deactivation and activation, others for offers fetching.
- Added changes in `offerAggregateOptions.js`, so users will not see offers from deactivated accounts. At the same time, if user requests his own offers like this `users/:id/offers` he will see it, even if he is deactivated. This way offers page won't be broken for deactivated users.
Below is a logic for showing user offers only from active accounts. The first condition checks if the user requests data is the user he want to get data for. If it is, we just skip that logic, so deactivated user can see …

Added account deactivation and activation logic

---

docs/category/category.yaml
src/test/integration/controllers/categoriesAggregateOptions.spec.js
src/utils/categories/categoriesAggregateOptions.js

- ### Categories are sorted by updatedAt field in descending order by default
- ### Categories can be sorted by totalOffers in arc/desc order via sort parameter
- ### Added tests for categoriesAggregateOptions
- ### Updated swagger docs for categories

Implemented sorting categories by totaloffers

---

docs/subject/subject-schema.yaml
docs/subject/subject.yaml
src/services/subject.js
src/test/integration/controllers/subject.spec.js

Now the GetSubjects response includes category appearance

Make GetSubjects endpoint return category appearance

---

src/utils/categories/categoriesAggregateOptions.js

Removed redundant skip and limit options to resolve conflicts

---

jest.config.js
src/test/integration/controllers/auth.spec.js
src/test/unit/services/token.spec.js
src/utils/mailer.js
src/validation/schemas/login.js

Fixed failing issues in tests for `email.spec.js` and `adminInvitation.spec.js`. The main problem was that creating and logging in **more than two users** in `auth.spec.js `caused issues in these two tests.
**Before update:**
**After update:**

Fixed failing tests on GitHub Actions (CI/Test_DEV) #812

---

src/consts/validation.js

Previously, when **updating the availability of a resource** for a specific date and attempting to save, the user was not presented with any feedback or error message. However, an `AxiosError` with code '`ERR_BAD_REQUEST`' was logged in the console, indicating a bad request error: 
Now, after changing the availability status of cooperation resources to a specific date and saving, the correct availability status is saved into the database:

Resolved issue with Date availability field type in cooperation resource #820

---

src/middlewares/coopSectionsValidation.js
src/models/cooperation.js
src/test/integration/controllers/cooperation.spec.js
src/test/unit/middlewares/coopSectionsValidation.spec.js

Resources are now returned in a single array `activities`, combining `lessons`, `attachments`, and `quizzes`. The `order` field has also been removed as per requirements:
##

Refactored cooperation model #788

---

src/test/unit/utils/validateQuestion.spec.js
src/utils/cooperations/sections/validateAttachment.js
src/utils/cooperations/sections/validateLesson.js
src/utils/cooperations/sections/validateQuestion.js
src/utils/cooperations/sections/validateQuiz.js

To fix this problem, a thorough investigation was conducted on both the frontend and backend sides to find the reason for the missing `resourceType` in the response **when getting a cooperation by ID**. In the end, it _was found that the validation on the backend side for resources like `lesson` and `attachment` was cutting off a few fields_, including the `resourceType` field. To fix this issue, the validation was changed to allow the `resourceType` field to be included.
After adding resources into cooperation with `resourceType` **lesson** or **attachment** and saving this cooperation, we try to refresh the page, but we can see that the icons for `lesson` and `attachment` are not proper. Also, in the response from the endpoint `http://localhost:3000/api/cooperations/:id`, we receive …

Fixed missing resourceType in response on getting cooperation by ID #848

---

docs/attachments/attachment.yaml
docs/lesson/lesson.yaml
docs/questions/question.yaml
docs/quiz/quiz.yaml
src/controllers/attachment.js
src/controllers/lesson.js
src/controllers/question.js
src/controllers/quiz.js
src/models/attachment.js
src/models/lesson.js
src/models/question.js
src/models/quiz.js

We can include resources with the existing field `isDuplicate: true` using new query param

Added isDuplicate field to resource models and updated get queries
